main:
  host: 0.0.0.0
  port: 5001
  flask_secret_key: secret!123
  database_path: project_data/Anagnorisis-app/database/project.db
  migrations_path: project_data/Anagnorisis-app/database/migrations
  models_path: project_data/Anagnorisis-app/models
  cache_path: cache
music:
  media_directory: ''
  media_formats:
  - .mp3
  - .flac
images:
  media_directory: ''
  media_formats:
  - .jpg
  - .jpeg
  - .png
  - .gif
  - .bmp
  - .webp
  - .tiff
videos:
  media_directory: ''
  media_formats:
  - .mp4
  - .webm
  - .avi
  - .mov
  - .wmv
  - .flv
  - .mkv
  - .ogv
text:
  media_directory: ''
  media_formats:
  - .txt
  - .md
